// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADTlLstg5sdi2GdJbSW3QS-f_65FWDkfc',
    appId: '1:677001024607:web:a6804546a4c7f5ae44b7ea',
    messagingSenderId: '677001024607',
    projectId: 'todofirestore-ae42d',
    authDomain: 'todofirestore-ae42d.firebaseapp.com',
    storageBucket: 'todofirestore-ae42d.firebasestorage.app',
    measurementId: 'G-3447ZBBPRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6mE4TnbC3jX8-yk51R4y_mu-Z4Gkijwc',
    appId: '1:677001024607:android:9014c79e77ddd87944b7ea',
    messagingSenderId: '677001024607',
    projectId: 'todofirestore-ae42d',
    storageBucket: 'todofirestore-ae42d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHSZQQFESfg25Rk6mLIo2JpxvafApQrq4',
    appId: '1:677001024607:ios:9615f84c4d93c1c144b7ea',
    messagingSenderId: '677001024607',
    projectId: 'todofirestore-ae42d',
    storageBucket: 'todofirestore-ae42d.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodo',
  );
}
